"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {Button} from "@/components/ui/Button";
import {parseDocumentCsv, type DocumentCsv} from "@/lib/documents/csv";
import {crmImportFields} from "@/lib/imports/fields";
import {importCsvBatch,previewCrmImport,type ImportEntityType,type ImportResult,type ImportProvenance} from "@/lib/imports/actions";
import styles from "@/components/documents/Documents.module.css";

type Source={csv:DocumentCsv;name:string;provenance?:Omit<ImportProvenance,"mapping">};
const norm=(v:string)=>v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
function proposal(headers:string[],target:ImportEntityType){const mapping:Record<string,number|null>={};for(const field of crmImportFields[target]){const matches=headers.map((h,i)=>field.aliases.includes(norm(h))?i:-1).filter(i=>i>=0);mapping[field.key]=matches.length===1?matches[0]:null;}return mapping;}
export function CsvImportWizard({initialSource,initialTarget="organizations"}:{initialSource?:Source;initialTarget?:ImportEntityType}) {
 const [target,setTarget]=useState<ImportEntityType>(initialTarget),[source,setSource]=useState<Source|null>(initialSource??null);
 const [mapping,setMapping]=useState<Record<string,number|null>>(initialSource?proposal(initialSource.csv.headers,initialTarget):{});
 const [mode,setMode]=useState<"skip"|"update"|"create">("skip"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [review,setReview]=useState<Awaited<ReturnType<typeof previewCrmImport>>|null>(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState<ImportResult|null>(null);
 const fields=crmImportFields[target];
 const rows=useMemo(()=>source?.csv.rows.map(row=>Object.fromEntries(fields.map(f=>[f.key,mapping[f.key]==null?"":row[mapping[f.key]!]??""])))??[],[source,fields,mapping]);
 const unresolved=fields.filter(f=>mapping[f.key]==null),resolved=fields.filter(f=>mapping[f.key]!=null);
 function reset(){setReview(null);setConfirmed(false);setResult(null);setError("");}
 function field(f:typeof fields[number]){return <label key={f.key} className={styles.field}>{f.label}{f.required?" · obligatoriu":""}<select value={mapping[f.key]??""} onChange={e=>{setMapping({...mapping,[f.key]:e.target.value===""?null:Number(e.target.value)});reset();}}><option value="">Nu importa acest câmp</option>{source?.csv.headers.map((h,i)=><option key={i} value={i}>{h||`Coloana ${i+1}`}</option>)}</select></label>;}
 async function load(file?:File){if(!file)return;reset();try{if(!/\.csv$/i.test(file.name)||file.size>2097152)throw Error("Selectează un CSV de cel mult 2 MB. Pentru XLSX, păstrează mai întâi workbook-ul în Documente.");const csv=parseDocumentCsv(new TextDecoder("utf-8",{fatal:true}).decode(await file.arrayBuffer()));setSource({csv,name:file.name});setMapping(proposal(csv.headers,target));}catch(e){setError(e instanceof Error?e.message:"Fișier indisponibil.");}}
 async function check(){setBusy(true);setError("");try{setReview(await previewCrmImport(target,rows));setConfirmed(false);}catch(e){setError(e instanceof Error?e.message:"Verificarea nu este disponibilă.");}finally{setBusy(false);}}
 async function commit(){if(!confirmed||!review||busy)return;setBusy(true);setError("");try{setResult(await importCsvBatch(target,rows,mode,source?.provenance?{...source.provenance,mapping}:undefined));}catch{setError("Confirmarea nu este disponibilă. Reîncearcă aceeași selecție pentru a verifica rezultatul, fără repetarea scrierilor.");}finally{setBusy(false);}}
 return <div className={styles.form}>
  {!initialSource?<><p className={styles.eyebrow}>Import opțional</p><h2>Alege datele și destinația</h2><p className={styles.meta}>Pentru păstrarea originalului și analiză ulterioară, <Link href="/documents/add" className="underline">adaugă documentul</Link>.</p><label className={styles.field}>Destinație<select value={target} onChange={e=>{const t=e.target.value as ImportEntityType;setTarget(t);setMapping(source?proposal(source.csv.headers,t):{});reset();}}><option value="organizations">Companii</option><option value="contacts">Contacte</option><option value="opportunities">Oportunități</option></select></label><label className={styles.field}>Selectează un fișier CSV<input type="file" accept=".csv" disabled={busy} onChange={e=>void load(e.target.files?.[0])}/></label></>:null}
  {error?<p role="alert" className={styles.error}>{error}</p>:null}
  {source&&!result?<fieldset disabled={busy} className={styles.form}><div><p className={styles.eyebrow}>{source.name} · {rows.length} rânduri</p><h2>Ce a înțeles ReveNew</h2><p className={styles.meta}>{resolved.length} câmpuri asociate. Verifică excepțiile înainte de confirmare.</p></div>
   <details><summary className="focus-ring">Câmpuri recunoscute ({resolved.length})</summary><div className={styles.form}>{resolved.map(field)}</div></details>
   {unresolved.length?<section className={styles.section}><h3>Câmpuri fără asociere</h3><p className={styles.meta}>Câmpurile opționale pot rămâne omise. Nicio valoare nu este inventată.</p><div className={styles.form}>{unresolved.map(field)}</div></section>:null}
   <details><summary className="focus-ring">Coloane omise din import</summary><p className={styles.meta}>{source.csv.headers.filter((_,i)=>!Object.values(mapping).includes(i)).join(" · ")||"Niciuna"}</p></details>
   <Button variant="secondary" disabled={fields.some(f=>f.required&&mapping[f.key]==null)||!rows.length} onClick={()=>void check()}>Verifică rândurile și potrivirile</Button>
   {review?<section className={styles.section}><h2>Ce se va întâmpla</h2><p className={styles.meta}>{review.filter(r=>r.state==="new").length} noi · {review.filter(r=>r.state==="exact").length} potriviri exacte · {review.filter(r=>r.state==="possible"||r.state==="conflict").length} potriviri de revizuit · {review.filter(r=>r.state==="invalid").length} invalide</p><div className={styles.gridScroll}><table className={styles.grid}><caption className="sr-only">Rânduri și potriviri înainte de confirmare</caption><thead><tr><th>Rând</th><th>Înregistrare</th><th>Verificare</th></tr></thead><tbody>{review.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.name||"Fără nume"}</td><td>{{new:"Nou",exact:"Potrivire exactă",possible:"Posibilă potrivire — verifică",conflict:"Conflict — corectează sursa",invalid:"Invalid"}[r.state]}</td></tr>)}</tbody></table></div>
   <label className={styles.field}>Potriviri exacte<select value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setConfirmed(false);}}><option value="skip">Omite înregistrările existente</option><option value="update">Actualizează câmpurile mapate după revizuire</option>{target==="opportunities"?<option value="create">Creează separat, inclusiv titlurile existente</option>:null}</select></label>
   <p className={styles.meta}>Validarea finală are loc la confirmare. Conflictele nu sunt unite automat. Valorile importate nu confirmă venituri sau acțiuni comerciale.</p><label className={styles.check}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Am verificat maparea, potrivirile și efectul ales. Confirm importul în această destinație.</label><Button disabled={!confirmed||review.some(r=>r.state==="conflict"||r.state==="possible")} onClick={()=>void commit()}>Confirmă importul</Button></section>:null}
  </fieldset>:null}
  {result?<section className={styles.section} aria-live="polite"><h2>{result.ok?result.duplicate?"Import deja înregistrat":"Import înregistrat":"Confirmare indisponibilă"}</h2><p>{result.error}</p><p>{result.created} create · {result.updated??0} actualizate · {result.skipped} omise · {result.rejected} respinse</p>{result.batchId?<p className={styles.meta}>Confirmare păstrată · {result.batchId}</p>:null}{result.errors.map(e=><p key={e.row} className={styles.meta}>Rândul {e.row}: {e.message}</p>)}{!result.ok?<Button variant="secondary" onClick={()=>void commit()} disabled={busy}>Verifică din nou aceeași confirmare</Button>:null}</section>:null}
 </div>;
}