export const PERMISSIONS = [
  "platform.admin.access",
  "platform.businesses.read_all",
  "platform.businesses.operate",
  "platform.usage.read_all",
  "platform.audit.read",
  "platform.system_health.read",
  "platform.integrations.read",
  "platform.technical_diagnostics.read",
  "platform.subscriptions.read_all",
  "platform.internal_tools.access",
  "workspace.read",
  "dashboard.read",
  "signals.read",
  "signals.create",
  "signals.update",
  "signals.convert",
  "signals.archive",
  "opportunities.read",
  "opportunities.create",
  "opportunities.update",
  "opportunities.analyze",
  "actions.read",
  "actions.create",
  "actions.update",
  "actions.complete",
  "documents.read",
  "documents.generate",
  "documents.update",
  "documents.mark_sent",
  "reports.read",
  "reports.export",
  "settings.read",
  "settings.update",
  "members.read",
  "members.manage",
  "billing.read",
  "billing.manage",
  "usage.read"
] as const;

export type Permission = (typeof PERMISSIONS)[number];
