export const canonicalCountryOptions = [
  { code: "AC", label: "Insula Ascension", callingCode: "+247" },
  { code: "AD", label: "Andorra", callingCode: "+376" },
  { code: "AE", label: "Emiratele Arabe Unite", callingCode: "+971" },
  { code: "AF", label: "Afganistan", callingCode: "+93" },
  { code: "AG", label: "Antigua și Barbuda", callingCode: "+1" },
  { code: "AI", label: "Anguilla", callingCode: "+1" },
  { code: "AL", label: "Albania", callingCode: "+355" },
  { code: "AM", label: "Armenia", callingCode: "+374" },
  { code: "AO", label: "Angola", callingCode: "+244" },
  { code: "AR", label: "Argentina", callingCode: "+54" },
  { code: "AS", label: "Samoa Americană", callingCode: "+1" },
  { code: "AT", label: "Austria", callingCode: "+43" },
  { code: "AU", label: "Australia", callingCode: "+61" },
  { code: "AW", label: "Aruba", callingCode: "+297" },
  { code: "AX", label: "Insulele Åland", callingCode: "+358" },
  { code: "AZ", label: "Azerbaidjan", callingCode: "+994" },
  { code: "BA", label: "Bosnia și Herțegovina", callingCode: "+387" },
  { code: "BB", label: "Barbados", callingCode: "+1" },
  { code: "BD", label: "Bangladesh", callingCode: "+880" },
  { code: "BE", label: "Belgia", callingCode: "+32" },
  { code: "BF", label: "Burkina Faso", callingCode: "+226" },
  { code: "BG", label: "Bulgaria", callingCode: "+359" },
  { code: "BH", label: "Bahrain", callingCode: "+973" },
  { code: "BI", label: "Burundi", callingCode: "+257" },
  { code: "BJ", label: "Benin", callingCode: "+229" },
  { code: "BL", label: "Saint-Barthélemy", callingCode: "+590" },
  { code: "BM", label: "Bermuda", callingCode: "+1" },
  { code: "BN", label: "Brunei", callingCode: "+673" },
  { code: "BO", label: "Bolivia", callingCode: "+591" },
  { code: "BQ", label: "Insulele Caraibe Olandeze", callingCode: "+599" },
  { code: "BR", label: "Brazilia", callingCode: "+55" },
  { code: "BS", label: "Bahamas", callingCode: "+1" },
  { code: "BT", label: "Bhutan", callingCode: "+975" },
  { code: "BW", label: "Botswana", callingCode: "+267" },
  { code: "BY", label: "Belarus", callingCode: "+375" },
  { code: "BZ", label: "Belize", callingCode: "+501" },
  { code: "CA", label: "Canada", callingCode: "+1" },
  { code: "CC", label: "Insulele Cocos (Keeling)", callingCode: "+61" },
  { code: "CD", label: "Congo - Kinshasa", callingCode: "+243" },
  { code: "CF", label: "Republica Centrafricană", callingCode: "+236" },
  { code: "CG", label: "Congo - Brazzaville", callingCode: "+242" },
  { code: "CH", label: "Elveția", callingCode: "+41" },
  { code: "CI", label: "Côte d’Ivoire", callingCode: "+225" },
  { code: "CK", label: "Insulele Cook", callingCode: "+682" },
  { code: "CL", label: "Chile", callingCode: "+56" },
  { code: "CM", label: "Camerun", callingCode: "+237" },
  { code: "CN", label: "China", callingCode: "+86" },
  { code: "CO", label: "Columbia", callingCode: "+57" },
  { code: "CR", label: "Costa Rica", callingCode: "+506" },
  { code: "CU", label: "Cuba", callingCode: "+53" },
  { code: "CV", label: "Capul Verde", callingCode: "+238" },
  { code: "CW", label: "Curaçao", callingCode: "+599" },
  { code: "CX", label: "Insula Christmas", callingCode: "+61" },
  { code: "CY", label: "Cipru", callingCode: "+357" },
  { code: "CZ", label: "Cehia", callingCode: "+420" },
  { code: "DE", label: "Germania", callingCode: "+49" },
  { code: "DJ", label: "Djibouti", callingCode: "+253" },
  { code: "DK", label: "Danemarca", callingCode: "+45" },
  { code: "DM", label: "Dominica", callingCode: "+1" },
  { code: "DO", label: "Republica Dominicană", callingCode: "+1" },
  { code: "DZ", label: "Algeria", callingCode: "+213" },
  { code: "EC", label: "Ecuador", callingCode: "+593" },
  { code: "EE", label: "Estonia", callingCode: "+372" },
  { code: "EG", label: "Egipt", callingCode: "+20" },
  { code: "EH", label: "Sahara Occidentală", callingCode: "+212" },
  { code: "ER", label: "Eritreea", callingCode: "+291" },
  { code: "ES", label: "Spania", callingCode: "+34" },
  { code: "ET", label: "Etiopia", callingCode: "+251" },
  { code: "FI", label: "Finlanda", callingCode: "+358" },
  { code: "FJ", label: "Fiji", callingCode: "+679" },
  { code: "FK", label: "Insulele Falkland (Insulele Malvine)", callingCode: "+500" },
  { code: "FM", label: "Micronezia", callingCode: "+691" },
  { code: "FO", label: "Insulele Feroe", callingCode: "+298" },
  { code: "FR", label: "Franța", callingCode: "+33" },
  { code: "GA", label: "Gabon", callingCode: "+241" },
  { code: "GB", label: "Regatul Unit", callingCode: "+44" },
  { code: "GD", label: "Grenada", callingCode: "+1" },
  { code: "GE", label: "Georgia", callingCode: "+995" },
  { code: "GF", label: "Guyana Franceză", callingCode: "+594" },
  { code: "GG", label: "Guernsey", callingCode: "+44" },
  { code: "GH", label: "Ghana", callingCode: "+233" },
  { code: "GI", label: "Gibraltar", callingCode: "+350" },
  { code: "GL", label: "Groenlanda", callingCode: "+299" },
  { code: "GM", label: "Gambia", callingCode: "+220" },
  { code: "GN", label: "Guineea", callingCode: "+224" },
  { code: "GP", label: "Guadelupa", callingCode: "+590" },
  { code: "GQ", label: "Guineea Ecuatorială", callingCode: "+240" },
  { code: "GR", label: "Grecia", callingCode: "+30" },
  { code: "GT", label: "Guatemala", callingCode: "+502" },
  { code: "GU", label: "Guam", callingCode: "+1" },
  { code: "GW", label: "Guineea-Bissau", callingCode: "+245" },
  { code: "GY", label: "Guyana", callingCode: "+592" },
  { code: "HK", label: "R.A.S. Hong Kong, China", callingCode: "+852" },
  { code: "HN", label: "Honduras", callingCode: "+504" },
  { code: "HR", label: "Croația", callingCode: "+385" },
  { code: "HT", label: "Haiti", callingCode: "+509" },
  { code: "HU", label: "Ungaria", callingCode: "+36" },
  { code: "ID", label: "Indonezia", callingCode: "+62" },
  { code: "IE", label: "Irlanda", callingCode: "+353" },
  { code: "IL", label: "Israel", callingCode: "+972" },
  { code: "IM", label: "Insula Man", callingCode: "+44" },
  { code: "IN", label: "India", callingCode: "+91" },
  { code: "IO", label: "Teritoriul Britanic din Oceanul Indian", callingCode: "+246" },
  { code: "IQ", label: "Irak", callingCode: "+964" },
  { code: "IR", label: "Iran", callingCode: "+98" },
  { code: "IS", label: "Islanda", callingCode: "+354" },
  { code: "IT", label: "Italia", callingCode: "+39" },
  { code: "JE", label: "Jersey", callingCode: "+44" },
  { code: "JM", label: "Jamaica", callingCode: "+1" },
  { code: "JO", label: "Iordania", callingCode: "+962" },
  { code: "JP", label: "Japonia", callingCode: "+81" },
  { code: "KE", label: "Kenya", callingCode: "+254" },
  { code: "KG", label: "Kârgâzstan", callingCode: "+996" },
  { code: "KH", label: "Cambodgia", callingCode: "+855" },
  { code: "KI", label: "Kiribati", callingCode: "+686" },
  { code: "KM", label: "Comore", callingCode: "+269" },
  { code: "KN", label: "Saint Kitts și Nevis", callingCode: "+1" },
  { code: "KP", label: "Coreea de Nord", callingCode: "+850" },
  { code: "KR", label: "Coreea de Sud", callingCode: "+82" },
  { code: "KW", label: "Kuweit", callingCode: "+965" },
  { code: "KY", label: "Insulele Cayman", callingCode: "+1" },
  { code: "KZ", label: "Kazahstan", callingCode: "+7" },
  { code: "LA", label: "Laos", callingCode: "+856" },
  { code: "LB", label: "Liban", callingCode: "+961" },
  { code: "LC", label: "Sfânta Lucia", callingCode: "+1" },
  { code: "LI", label: "Liechtenstein", callingCode: "+423" },
  { code: "LK", label: "Sri Lanka", callingCode: "+94" },
  { code: "LR", label: "Liberia", callingCode: "+231" },
  { code: "LS", label: "Lesotho", callingCode: "+266" },
  { code: "LT", label: "Lituania", callingCode: "+370" },
  { code: "LU", label: "Luxemburg", callingCode: "+352" },
  { code: "LV", label: "Letonia", callingCode: "+371" },
  { code: "LY", label: "Libia", callingCode: "+218" },
  { code: "MA", label: "Maroc", callingCode: "+212" },
  { code: "MC", label: "Monaco", callingCode: "+377" },
  { code: "MD", label: "Republica Moldova", callingCode: "+373" },
  { code: "ME", label: "Muntenegru", callingCode: "+382" },
  { code: "MF", label: "Sfântul Martin", callingCode: "+590" },
  { code: "MG", label: "Madagascar", callingCode: "+261" },
  { code: "MH", label: "Insulele Marshall", callingCode: "+692" },
  { code: "MK", label: "Macedonia de Nord", callingCode: "+389" },
  { code: "ML", label: "Mali", callingCode: "+223" },
  { code: "MM", label: "Myanmar (Birmania)", callingCode: "+95" },
  { code: "MN", label: "Mongolia", callingCode: "+976" },
  { code: "MO", label: "R.A.S. Macao, China", callingCode: "+853" },
  { code: "MP", label: "Insulele Mariane de Nord", callingCode: "+1" },
  { code: "MQ", label: "Martinica", callingCode: "+596" },
  { code: "MR", label: "Mauritania", callingCode: "+222" },
  { code: "MS", label: "Montserrat", callingCode: "+1" },
  { code: "MT", label: "Malta", callingCode: "+356" },
  { code: "MU", label: "Mauritius", callingCode: "+230" },
  { code: "MV", label: "Maldive", callingCode: "+960" },
  { code: "MW", label: "Malawi", callingCode: "+265" },
  { code: "MX", label: "Mexic", callingCode: "+52" },
  { code: "MY", label: "Malaysia", callingCode: "+60" },
  { code: "MZ", label: "Mozambic", callingCode: "+258" },
  { code: "NA", label: "Namibia", callingCode: "+264" },
  { code: "NC", label: "Noua Caledonie", callingCode: "+687" },
  { code: "NE", label: "Niger", callingCode: "+227" },
  { code: "NF", label: "Insula Norfolk", callingCode: "+672" },
  { code: "NG", label: "Nigeria", callingCode: "+234" },
  { code: "NI", label: "Nicaragua", callingCode: "+505" },
  { code: "NL", label: "Țările de Jos", callingCode: "+31" },
  { code: "NO", label: "Norvegia", callingCode: "+47" },
  { code: "NP", label: "Nepal", callingCode: "+977" },
  { code: "NR", label: "Nauru", callingCode: "+674" },
  { code: "NU", label: "Niue", callingCode: "+683" },
  { code: "NZ", label: "Noua Zeelandă", callingCode: "+64" },
  { code: "OM", label: "Oman", callingCode: "+968" },
  { code: "PA", label: "Panama", callingCode: "+507" },
  { code: "PE", label: "Peru", callingCode: "+51" },
  { code: "PF", label: "Polinezia Franceză", callingCode: "+689" },
  { code: "PG", label: "Papua-Noua Guinee", callingCode: "+675" },
  { code: "PH", label: "Filipine", callingCode: "+63" },
  { code: "PK", label: "Pakistan", callingCode: "+92" },
  { code: "PL", label: "Polonia", callingCode: "+48" },
  { code: "PM", label: "Saint-Pierre și Miquelon", callingCode: "+508" },
  { code: "PR", label: "Puerto Rico", callingCode: "+1" },
  { code: "PS", label: "Teritoriile Palestiniene", callingCode: "+970" },
  { code: "PT", label: "Portugalia", callingCode: "+351" },
  { code: "PW", label: "Palau", callingCode: "+680" },
  { code: "PY", label: "Paraguay", callingCode: "+595" },
  { code: "QA", label: "Qatar", callingCode: "+974" },
  { code: "RE", label: "Réunion", callingCode: "+262" },
  { code: "RO", label: "România", callingCode: "+40" },
  { code: "RS", label: "Serbia", callingCode: "+381" },
  { code: "RU", label: "Rusia", callingCode: "+7" },
  { code: "RW", label: "Rwanda", callingCode: "+250" },
  { code: "SA", label: "Arabia Saudită", callingCode: "+966" },
  { code: "SB", label: "Insulele Solomon", callingCode: "+677" },
  { code: "SC", label: "Seychelles", callingCode: "+248" },
  { code: "SD", label: "Sudan", callingCode: "+249" },
  { code: "SE", label: "Suedia", callingCode: "+46" },
  { code: "SG", label: "Singapore", callingCode: "+65" },
  { code: "SH", label: "Sfânta Elena", callingCode: "+290" },
  { code: "SI", label: "Slovenia", callingCode: "+386" },
  { code: "SJ", label: "Svalbard și Jan Mayen", callingCode: "+47" },
  { code: "SK", label: "Slovacia", callingCode: "+421" },
  { code: "SL", label: "Sierra Leone", callingCode: "+232" },
  { code: "SM", label: "San Marino", callingCode: "+378" },
  { code: "SN", label: "Senegal", callingCode: "+221" },
  { code: "SO", label: "Somalia", callingCode: "+252" },
  { code: "SR", label: "Suriname", callingCode: "+597" },
  { code: "SS", label: "Sudanul de Sud", callingCode: "+211" },
  { code: "ST", label: "São Tomé și Príncipe", callingCode: "+239" },
  { code: "SV", label: "El Salvador", callingCode: "+503" },
  { code: "SX", label: "Sint-Maarten", callingCode: "+1" },
  { code: "SY", label: "Siria", callingCode: "+963" },
  { code: "SZ", label: "Eswatini", callingCode: "+268" },
  { code: "TA", label: "Tristan da Cunha", callingCode: "+290" },
  { code: "TC", label: "Insulele Turks și Caicos", callingCode: "+1" },
  { code: "TD", label: "Ciad", callingCode: "+235" },
  { code: "TG", label: "Togo", callingCode: "+228" },
  { code: "TH", label: "Thailanda", callingCode: "+66" },
  { code: "TJ", label: "Tadjikistan", callingCode: "+992" },
  { code: "TK", label: "Tokelau", callingCode: "+690" },
  { code: "TL", label: "Timor-Leste", callingCode: "+670" },
  { code: "TM", label: "Turkmenistan", callingCode: "+993" },
  { code: "TN", label: "Tunisia", callingCode: "+216" },
  { code: "TO", label: "Tonga", callingCode: "+676" },
  { code: "TR", label: "Turcia", callingCode: "+90" },
  { code: "TT", label: "Trinidad și Tobago", callingCode: "+1" },
  { code: "TV", label: "Tuvalu", callingCode: "+688" },
  { code: "TW", label: "Taiwan", callingCode: "+886" },
  { code: "TZ", label: "Tanzania", callingCode: "+255" },
  { code: "UA", label: "Ucraina", callingCode: "+380" },
  { code: "UG", label: "Uganda", callingCode: "+256" },
  { code: "US", label: "Statele Unite ale Americii", callingCode: "+1" },
  { code: "UY", label: "Uruguay", callingCode: "+598" },
  { code: "UZ", label: "Uzbekistan", callingCode: "+998" },
  { code: "VA", label: "Statul Cetății Vaticanului", callingCode: "+39" },
  { code: "VC", label: "Saint Vincent și Grenadinele", callingCode: "+1" },
  { code: "VE", label: "Venezuela", callingCode: "+58" },
  { code: "VG", label: "Insulele Virgine Britanice", callingCode: "+1" },
  { code: "VI", label: "Insulele Virgine Americane", callingCode: "+1" },
  { code: "VN", label: "Vietnam", callingCode: "+84" },
  { code: "VU", label: "Vanuatu", callingCode: "+678" },
  { code: "WF", label: "Wallis și Futuna", callingCode: "+681" },
  { code: "WS", label: "Samoa", callingCode: "+685" },
  { code: "XK", label: "Kosovo", callingCode: "+383" },
  { code: "YE", label: "Yemen", callingCode: "+967" },
  { code: "YT", label: "Mayotte", callingCode: "+262" },
  { code: "ZA", label: "Africa de Sud", callingCode: "+27" },
  { code: "ZM", label: "Zambia", callingCode: "+260" },
  { code: "ZW", label: "Zimbabwe", callingCode: "+263" }
] as const;

export type CanonicalCountryCode = (typeof canonicalCountryOptions)[number]["code"];

export const canonicalCountryCodes = canonicalCountryOptions.map((country) => country.code) as CanonicalCountryCode[];
